apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-orchestrator
  namespace: streamvault
  labels: { app.kubernetes.io/name: notification-orchestrator, streamvault.io/domain: communications }
data:
  LOG_LEVEL: info
  PORT: "50320"
