apiVersion: v1
kind: Service
metadata:
  name: rating-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: rating-service, streamvault.io/domain: social }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50261, targetPort: 50261 }]
  selector: { app.kubernetes.io/name: rating-service }
