apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata: { name: streamvault-dns-error, namespace: chaos-mesh }
spec:
  action: error
  mode: all
  patterns: ["*.streamvault.svc.cluster.local"]
  selector: { namespaces: [streamvault] }
  duration: 2m
