apiVersion: v1
kind: Service
metadata:
  name: licence-server
  namespace: streamvault
  labels: { app.kubernetes.io/name: licence-server, streamvault.io/domain: drm }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50080, targetPort: 50080 }]
  selector: { app.kubernetes.io/name: licence-server }
