apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-cache
  namespace: streamvault
  labels: { app.kubernetes.io/name: edge-cache, streamvault.io/domain: cdn }
data:
  LOG_LEVEL: info
  PORT: "50102"
