apiVersion: v1
kind: Service
metadata:
  name: ad-server
  namespace: streamvault
  labels: { app.kubernetes.io/name: ad-server, streamvault.io/domain: ad }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50220, targetPort: 50220 }]
  selector: { app.kubernetes.io/name: ad-server }
