apiVersion: v1
kind: Service
metadata:
  name: engagement-analytics
  namespace: streamvault
  labels: { app.kubernetes.io/name: engagement-analytics, streamvault.io/domain: analytics }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50302, targetPort: 50302 }]
  selector: { app.kubernetes.io/name: engagement-analytics }
