image: { repository: harbor.streamvault.internal/streamvault/cdn-orchestrator, tag: latest, pullPolicy: IfNotPresent }
replicaCount: 4
service: { type: ClusterIP, port: 50050 }
resources: { requests: { cpu: 300m, memory: 512Mi }, limits: { cpu: 2000m, memory: 2Gi } }
env: { LOG_LEVEL: info, PORT: "50050", CF_ZONE_ID: "", AWS_DISTRIBUTION_ID: "" }
serviceAccount: { create: true, name: cdn-orchestrator, annotations: {} }
podSecurityContext: { runAsNonRoot: true, runAsUser: 1000, fsGroup: 1000 }
containerSecurityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: { drop: ["ALL"] } }
domain: cdn
