apiVersion: v1
kind: Service
metadata:
  name: churn-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: churn-service, streamvault.io/domain: subscription }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50183, targetPort: 50183 }]
  selector: { app.kubernetes.io/name: churn-service }
