apiVersion: v1
kind: ConfigMap
metadata:
  name: i18n-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: i18n-service, streamvault.io/domain: platform }
data:
  LOG_LEVEL: info
  PORT: "51012"
