apiVersion: v1
kind: Service
metadata:
  name: revenue-analytics
  namespace: streamvault
  labels: { app.kubernetes.io/name: revenue-analytics, streamvault.io/domain: analytics }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50303, targetPort: 50303 }]
  selector: { app.kubernetes.io/name: revenue-analytics }
