apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: streamvault-azure
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/prabhat-roy/StreamVault.git
        revision: HEAD
        directories:
          - path: helm/charts/*
  template:
    metadata:
      name: '{{path.basename}}-azure'
      labels: { cloud: azure, streamvault.io/managed-by: argocd }
    spec:
      project: streamvault
      source:
        repoURL: https://github.com/prabhat-roy/StreamVault.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles: [values.yaml, values-azure.yaml]
      destination:
        server: https://kubernetes.default.svc
        namespace: streamvault
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions: [CreateNamespace=true, ServerSideApply=true]
