apiVersion: v1
kind: Service
metadata:
  name: trending-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: trending-service, streamvault.io/domain: personalisation }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50242, targetPort: 50242 }]
  selector: { app.kubernetes.io/name: trending-service }
