apiVersion: v1
kind: ConfigMap
metadata:
  name: watchlist-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: watchlist-service, streamvault.io/domain: social }
data:
  LOG_LEVEL: info
  PORT: "50260"
