apiVersion: v1
kind: Service
metadata:
  name: watchlist-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: watchlist-service, streamvault.io/domain: social }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50260, targetPort: 50260 }]
  selector: { app.kubernetes.io/name: watchlist-service }
