apiVersion: v1
kind: Service
metadata:
  name: continue-watching
  namespace: streamvault
  labels: { app.kubernetes.io/name: continue-watching, streamvault.io/domain: personalisation }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50241, targetPort: 50241 }]
  selector: { app.kubernetes.io/name: continue-watching }
