apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: { name: playback-orchestrator, namespace: streamvault }
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: playback-orchestrator }
  minReplicas: 6
  maxReplicas: 120
  metrics:
    - type: Resource
      resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } }
