apiVersion: v1
kind: Service
metadata:
  name: notification-preferences-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: notification-preferences-service, streamvault.io/domain: platform }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 51005, targetPort: 51005 }]
  selector: { app.kubernetes.io/name: notification-preferences-service }
