apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: profile-service, streamvault.io/domain: identity }
data:
  LOG_LEVEL: info
  PORT: "50021"
