apiVersion: v1
kind: Service
metadata:
  name: playback-analytics
  namespace: streamvault
  labels: { app.kubernetes.io/name: playback-analytics, streamvault.io/domain: analytics }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50301, targetPort: 50301 }]
  selector: { app.kubernetes.io/name: playback-analytics }
