serviceAccount: { annotations: { iam.gke.io/gcp-service-account: streamvault-transcoding@streamvault.iam.gserviceaccount.com } }
storageClass: pd-balanced
nodeSelector: { cloud.google.com/gke-accelerator: nvidia-tesla-t4, cloud.google.com/gke-spot: "true" }
