serviceAccount: { annotations: { azure.workload.identity/client-id: 00000000-0000-0000-0000-000000000000 } }
storageClass: managed-csi
nodeSelector: { agentpool: gpuspot, kubernetes.azure.com/scalesetpriority: spot }
