apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: streamvault
  labels: { app.kubernetes.io/name: api-gateway, streamvault.io/domain: platform }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50000, targetPort: 50000 }]
  selector: { app.kubernetes.io/name: api-gateway }
