apiVersion: v1
kind: ConfigMap
metadata:
  name: ad-insertion
  namespace: streamvault
  labels: { app.kubernetes.io/name: ad-insertion, streamvault.io/domain: playback }
data:
  LOG_LEVEL: info
  PORT: "50163"
