apiVersion: v1
kind: ConfigMap
metadata:
  name: ad-analytics
  namespace: streamvault
  labels: { app.kubernetes.io/name: ad-analytics, streamvault.io/domain: ad }
data:
  LOG_LEVEL: info
  PORT: "50223"
