apiVersion: v1
kind: Service
metadata:
  name: ad-analytics
  namespace: streamvault
  labels: { app.kubernetes.io/name: ad-analytics, streamvault.io/domain: ad }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50223, targetPort: 50223 }]
  selector: { app.kubernetes.io/name: ad-analytics }
