apiVersion: v1
kind: Service
metadata:
  name: parental-controls
  namespace: streamvault
  labels: { app.kubernetes.io/name: parental-controls, streamvault.io/domain: identity }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50022, targetPort: 50022 }]
  selector: { app.kubernetes.io/name: parental-controls }
