apiVersion: v1
kind: ConfigMap
metadata:
  name: comment-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: comment-service, streamvault.io/domain: social }
data:
  LOG_LEVEL: info
  PORT: "50262"
