apiVersion: v1
kind: Service
metadata:
  name: comment-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: comment-service, streamvault.io/domain: social }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50262, targetPort: 50262 }]
  selector: { app.kubernetes.io/name: comment-service }
