apiVersion: v1
kind: ConfigMap
metadata:
  name: geo-routing
  namespace: streamvault
  labels: { app.kubernetes.io/name: geo-routing, streamvault.io/domain: cdn }
data:
  LOG_LEVEL: info
  PORT: "50103"
