apiVersion: v1
kind: Service
metadata:
  name: geo-routing
  namespace: streamvault
  labels: { app.kubernetes.io/name: geo-routing, streamvault.io/domain: cdn }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50103, targetPort: 50103 }]
  selector: { app.kubernetes.io/name: geo-routing }
