apiVersion: v1
kind: ConfigMap
metadata:
  name: watch-party-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: watch-party-service, streamvault.io/domain: social }
data:
  LOG_LEVEL: info
  PORT: "50263"
