apiVersion: v1
kind: ConfigMap
metadata:
  name: upload-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: upload-service, streamvault.io/domain: creator }
data:
  LOG_LEVEL: info
  PORT: "50200"
