apiVersion: v1
kind: Service
metadata:
  name: abr-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: abr-service, streamvault.io/domain: cdn }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50104, targetPort: 50104 }]
  selector: { app.kubernetes.io/name: abr-service }
