apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: search-service, streamvault.io/domain: catalogue }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50140, targetPort: 50140 }]
  selector: { app.kubernetes.io/name: search-service }
