apiVersion: v1
kind: Service
metadata:
  name: search-ranking
  namespace: streamvault
  labels: { app.kubernetes.io/name: search-ranking, streamvault.io/domain: personalisation }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50243, targetPort: 50243 }]
  selector: { app.kubernetes.io/name: search-ranking }
