apiVersion: v1
kind: Service
metadata:
  name: origin-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: origin-service, streamvault.io/domain: cdn }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50101, targetPort: 50101 }]
  selector: { app.kubernetes.io/name: origin-service }
