apiVersion: v1
kind: Pod
metadata:
  labels: { jenkins: agent, project: streamvault }
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
    - name: tools
      image: streamvault/jenkins-agent:latest
      tty: true
      command: ["sleep","infinity"]
    - name: docker
      image: docker:27-dind
      securityContext: { privileged: true }
    - name: ffmpeg
      image: jrottenberg/ffmpeg:6.1-ubuntu
      tty: true
      command: ["sleep","infinity"]
