apiVersion: v1
kind: ConfigMap
metadata:
  name: targeting-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: targeting-service, streamvault.io/domain: ad }
data:
  LOG_LEVEL: info
  PORT: "50222"
