apiVersion: v1
kind: Service
metadata:
  name: payment-gateway
  namespace: streamvault
  labels: { app.kubernetes.io/name: payment-gateway, streamvault.io/domain: subscription }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50181, targetPort: 50181 }]
  selector: { app.kubernetes.io/name: payment-gateway }
