apiVersion: v1
kind: ConfigMap
metadata:
  name: watermarking-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: watermarking-service, streamvault.io/domain: drm }
data:
  LOG_LEVEL: info
  PORT: "50081"
