apiVersion: v1
kind: Service
metadata:
  name: watermarking-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: watermarking-service, streamvault.io/domain: drm }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50081, targetPort: 50081 }]
  selector: { app.kubernetes.io/name: watermarking-service }
