apiVersion: v1
kind: ConfigMap
metadata:
  name: mfa-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: mfa-service, streamvault.io/domain: identity }
data:
  LOG_LEVEL: info
  PORT: "50023"
