apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: email-service, streamvault.io/domain: communications }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50321, targetPort: 50321 }]
  selector: { app.kubernetes.io/name: email-service }
