apiVersion: v1
kind: Service
metadata:
  name: episode-service
  namespace: streamvault
  labels: { app.kubernetes.io/name: episode-service, streamvault.io/domain: catalogue }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50142, targetPort: 50142 }]
  selector: { app.kubernetes.io/name: episode-service }
